version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.21.6
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
