version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
