version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app
      - /app/node_modules
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf