version: "3.3"

services:
  portal-frontend-nginx:
    container_name: portal-frontend-nginx
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    stdin_open: true
    environment:
      - NGINX_API_HOST
      - NGINX_API_PORTAL
      - NGINX_URL_DOMAIN
    volumes:
      - /app
      - /app/node_modules
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "443:443"
      - "80:80"