version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - "80:3000"
