version: '3.3'

services:
  nginx:
    container_name: nginx-frontend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
      - /etc/letsencrypt/:/etc/letsencrypt/