version: '3.3'

services:
#  frontend:
#    container_name: frontend
#    build:
#      dockerfile: Dockerfile
#      context: .
#    volumes:
#      - /app
#      - /app/node_modules
#      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
#    ports:
#      - "3000:3000"
  nginx:
    container_name: nginx-frontend
    image: nginx:1.21.6
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /app
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /app/build:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf