version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - "80:3000"
#  nginx:
#    container_name: nginx
#    image: nginx:1.21.6
#    depends_on:
#      - frontend
#    restart: always
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    ports:
#      - "80:80"
#      - "443:443"
